namespace DomainAI.Agents.Reporting.Domain;

/// <summary>
/// Aggregate root for a generated report within the Reporting bounded context.
/// </summary>
public sealed class Report
{
    private readonly List<ReportSection> _sections = new();

    public string Title { get; private set; }
    public string ExecutiveSummary { get; private set; } = string.Empty;
    public DateTimeOffset GeneratedAt { get; private set; } = DateTimeOffset.UtcNow;
    public IReadOnlyList<ReportSection> Sections => _sections.AsReadOnly();

    private Report(string title)
    {
        Title = title;
    }

    public static Report Create(string title) => new(title);

    public void SetExecutiveSummary(string summary) => ExecutiveSummary = summary;

    public void AddSection(ReportSection section) => _sections.Add(section);

    public string Render()
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"# {Title}");
        sb.AppendLine($"*Generated: {GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC*");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine("## Executive Summary");
        sb.AppendLine(ExecutiveSummary);
        sb.AppendLine();

        foreach (var section in _sections.OrderBy(s => s.Order))
        {
            sb.AppendLine($"## {section.Title}");
            sb.AppendLine($"*Source: {section.SourceAgent}*");
            sb.AppendLine();
            sb.AppendLine(section.Content);
            sb.AppendLine();
        }

        sb.AppendLine("---");
        sb.AppendLine("*Report generated by DomainAI Multi-Agent System*");
        return sb.ToString();
    }
}
